version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
        name: Install Python Dependencies
        command: [
          echo 'export PATH=~/.local/bin/pytest' >> $BASH_ENV && Source $BASH_ENV
          pip install --user -r requirements.txt      
      - run:
        name: Run Unit Tests
        command: [
          pytest ----junitxml=test-reports/junit.xml --html=test-report
      
      
